// <auto-generated />
using Chat.Host.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chat.Host.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("message_sentiment_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("messsage_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("Chat.Host.Datas.Entities.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "messsage_hilo");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SentimentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentimentId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Chat.Host.Datas.Entities.SentimentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "message_sentiment_hilo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Sentiment", (string)null);
                });

            modelBuilder.Entity("Chat.Host.Datas.Entities.MessageEntity", b =>
                {
                    b.HasOne("Chat.Host.Datas.Entities.SentimentEntity", "Sentiment")
                        .WithMany()
                        .HasForeignKey("SentimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentiment");
                });
#pragma warning restore 612, 618
        }
    }
}
